name: Deploy
on:
  push:
    branches:
      - dev

  pull_request:
    types: [closed]

jobs:
  deploy-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Bun Installer
        uses: oven-sh/setup-bun@v1

      - name: Install Dependancies
        run: bun install

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh/
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          echo "${{ secrets.SSH_PUBLIC_KEY }}" > ~/.ssh/id_rsa.pub
          chmod 600 ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa.pub
          ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      - name: Copy files to server
        run: |
          rsync -qrm . ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/home/${{ secrets.SSH_USER }}/health-bot

      - name: Run Migrations
        run: |
          echo ${{ secrets.SSH_USER_PASS }} | ssh -tt ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "source ~/.nvm/nvm.sh && cd /home/${{ secrets.SSH_USER }}/health-bot-dev/ && /home/${{ secrets.SSH_USER }}/.bun/bin/bun x prisma migrate deploy"

      - name: Run Module Generation
        run: |
          echo ${{ secrets.SSH_USER_PASS }} | ssh -tt ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "source ~/.nvm/nvm.sh && cd /home/${{ secrets.SSH_USER }}/health-bot-dev/ && /home/${{ secrets.SSH_USER }}/.bun/bin/bun x prisma generate"

      - name: Restart Daemon
        run: |
          echo ${{ secrets.SSH_USER_PASS }} | ssh -tt ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "sudo chmod +x /home/${{ secrets.SSH_USER }}/health-bot-dev/scripts/restart.sh"
          echo ${{ secrets.SSH_USER_PASS }} | ssh -tt ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "sudo bash /home/${{ secrets.SSH_USER }}/health-bot-dev/scripts/restart.sh"
